---
title: "Gov 50 Final Project"
author: "Alex Chou"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

Do children who spend an average of more than 2 hours on screens daily have lower mental health? I theorize that children who have an addiction to their screens are more likely to exhibit worse mental health. My dataset it titled "The Effect of Screentime on the Mental Health of Children." This data is from 2020 and comes from the National Survey of Children's Health. Screentime is measured by how long, in hours, children spend on their phone. This could be subset into time specifically spent on social media apps — Facebook, Snapchat, Instagram, X, etc. On the other hand, mental health is difficult to objectively measure, though medical diagnoses of depression/anxiety, occurrences of headaches or insomnia, or contentious relationships with family members could all be metrics. Increasingly, we are seeing how screentime can be detrimental to mood and self-perception in numerous ways. For example, overexposure to media on dismaying global events may lead to feelings of hopelessness, obsessions over celebrities may lead to unhealthy body images, and posts from friends may lead to jealousy or fear of missing out (FOMO). It would be unsurprising, then, that those who have regular interactions with these kinds of digital materials are more likely to have negative or unsatisfied outlooks on the world and themselves. If I observe that children who spend more than 2 hours on screens have better or the same mental health as children who spend less than 2 hours, this would provide evidence against my hypothesis. When I run my regression of screentime on the mental health indicator variable, a positive, significant coefficient would indicate support for my hypothesis.


```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)

file <- read.csv("Screentime_v_Mental_Health_Dataset.csv")
file

screen_time <- c("Less than 1 hour", "1 hour", "2 hours", "3 hours", 
                      "4 or more hours")

filtered_data <- file |>
  mutate(
    treatment = if_else(Mental.Health.Treatment == "Needs Treatment", 1, 0)
  ) |>
  select(Screentime, treatment) |>
  group_by(Screentime) |>
  summarize(treatment_mean = mean(treatment, na.rm = TRUE)) |>
  ggplot() +
  geom_col(aes(x = factor(Screentime, screen_time), y = treatment_mean, fill = Screentime), stat = "identity") +
  labs(x = "Screen Time (hours)",
       y = "Average Need for Mental Health Treatment",
       title = "Screen Time Impact on Mental Health",
       source = "National Survey of Children’s Health (NSCH), 2020")
  

filtered_data

```




